# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OwuiProxy < Formula
  desc "Local Ollama-compatible API proxy for Open WebUI"
  homepage "https://github.com/varmakarthik12/owui-proxy"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/varmakarthik12/owui-proxy/releases/download/v0.1.0/owui-proxy_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "e2c80677d74fadd06c97a21e2c15042161e65b340a918c42ce2936c58cb7447a"

      define_method(:install) do
        bin.install "owui-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/varmakarthik12/owui-proxy/releases/download/v0.1.0/owui-proxy_0.1.0_Darwin_arm64.tar.gz"
      sha256 "886d9e55f8f17848a0ea1339402bb7db55c7170747f32a147770ab2d0c69289c"

      define_method(:install) do
        bin.install "owui-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/varmakarthik12/owui-proxy/releases/download/v0.1.0/owui-proxy_0.1.0_Linux_x86_64.tar.gz"
      sha256 "f6e8e56b511961b02cc6b4bc5d1d885e844f1c6a40899a329b437daae0239c34"
      define_method(:install) do
        bin.install "owui-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varmakarthik12/owui-proxy/releases/download/v0.1.0/owui-proxy_0.1.0_Linux_arm64.tar.gz"
      sha256 "478cc360c6c1c4d64755cc915ef1ca903bbbb04d9f174ff6d149679897914c0b"
      define_method(:install) do
        bin.install "owui-proxy"
      end
    end
  end

  test do
    system "#{bin}/owui-proxy", "version"
  end
end
