# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OwuiProxy < Formula
  desc "Local Ollama-compatible API proxy for Open WebUI"
  homepage "https://github.com/varmakarthik12/owui-proxy"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/varmakarthik12/owui-proxy/releases/download/v0.1.1/owui-proxy_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "27fa1515c6a84e741a61cbcef2aaa8da0cca8b9ab7ebdec576dd8acddbbf338e"

      define_method(:install) do
        bin.install "owui-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/varmakarthik12/owui-proxy/releases/download/v0.1.1/owui-proxy_0.1.1_Darwin_arm64.tar.gz"
      sha256 "125c7df47461273995d16732baabd9a5ea52c0abca2ecbe2c4cf70e1635ee0cc"

      define_method(:install) do
        bin.install "owui-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/varmakarthik12/owui-proxy/releases/download/v0.1.1/owui-proxy_0.1.1_Linux_x86_64.tar.gz"
      sha256 "a34b0bae02278b3d0b5380cb73df6a17368345e06e37846b7b2435572deeede8"
      define_method(:install) do
        bin.install "owui-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varmakarthik12/owui-proxy/releases/download/v0.1.1/owui-proxy_0.1.1_Linux_arm64.tar.gz"
      sha256 "58fd50e197a34716001ba3fd62db496f64eadd2fbeebff071e6f52d59221e7b4"
      define_method(:install) do
        bin.install "owui-proxy"
      end
    end
  end

  test do
    system "#{bin}/owui-proxy", "version"
  end
end
