# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OwuiProxy < Formula
  desc "Local Ollama-compatible API proxy for Open WebUI"
  homepage "https://github.com/varmakarthik12/owui-proxy"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/varmakarthik12/owui-proxy/releases/download/v0.1.1/owui-proxy_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "3d5e64bbabe1a7c00df5b74713f4a11f101fba872f8eb15aa7ad1b4a94470104"

      define_method(:install) do
        bin.install "owui-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/varmakarthik12/owui-proxy/releases/download/v0.1.1/owui-proxy_0.1.1_Darwin_arm64.tar.gz"
      sha256 "b4ff04807b95bf08525827bafc2385b96c4708dfa3177ee6df40058cf0765631"

      define_method(:install) do
        bin.install "owui-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/varmakarthik12/owui-proxy/releases/download/v0.1.1/owui-proxy_0.1.1_Linux_x86_64.tar.gz"
      sha256 "02204be36ca3a6256f739b9b40b679a45515a6dba8bfe6577625e8cb1cb7502a"
      define_method(:install) do
        bin.install "owui-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varmakarthik12/owui-proxy/releases/download/v0.1.1/owui-proxy_0.1.1_Linux_arm64.tar.gz"
      sha256 "4e4097f5d2316ddcdc288139573424f9ffc787f3f0f669fcf524a527dfacc64a"
      define_method(:install) do
        bin.install "owui-proxy"
      end
    end
  end

  test do
    system "#{bin}/owui-proxy", "version"
  end
end
